
breakneck = Hike.create(name: "Breakneck Ridge", location: "NY", difficulty: "Advanced", distance: 6.5, likes: 0)
capitol = Hike.create(name: "Capitol Peak", location: "CO", difficulty: "Advanced", distance: 13, likes: 0)
mtB = Hike.create(name: "Mt. Beacon", location: "NY", difficulty: "Intermediate", distance: 4, likes: 0)
longs = Hike.create(name: "Long's Peak", location: "CO", difficulty: "Advanced", distance: 14, likes: 0)
maroon = Hike.create(name: "Maroon Peak", location: "CO", difficulty: "Advanced", distance: 12, likes: 0)
levy = Hike.create(name: "Levy Trail", location: "NY", difficulty: "Beginner", distance: 7, likes: 0)
dem = Hike.create(name: "Mt. Democrat", location: "CO", difficulty: "Intermediate", distance: 3.5, likes: 0)
wash = Hike.create(name: "Mt. Washington", location: "NY", difficulty: "Advanced", distance: 13, likes: 0)
kaaterskill = Hike.create(name: "Kaaterskill Falls", location: "NY", difficulty: "Beginner", distance: 3, likes: 0)

Hiker.create(hikername: "Karin", password_digest: "dolly", location: "Long Island, NY", admin: true)
Hiker.create(hikername: "Dolly", password_digest: "bunny", location: "Long Island, NY", admin: true)
Hiker.create(hikername: "Dexter", password_digest: "bunny", location: "Long Island, NY", admin: false)
Hiker.create(hikername: "Roxy", password_digest: "bunny", location: "Long Island, NY", admin: false)